# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTest001():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def wait_for_window(self, timeout=2):
        time.sleep(round(timeout / 1000))
        wh_now = self.driver.window_handles
        wh_then = self.vars["window_handles"]
        if len(wh_now) > len(wh_then):
            return set(wh_now).difference(set(wh_then)).pop()

    def test_test001(self):
        # Test name: Test001
        # Step # | name | target | value | comment
        # 1 | open | / |  |
        self.driver.get("https://www.baidu.com/")
        # 2 | setWindowSize | 1051x798 |  |
        self.driver.set_window_size(1051, 798)
        # 3 | click | id=kw |  |
        self.driver.find_element(By.ID, "kw").click()
        # 4 | type | id=kw | 钟万顺 |
        self.driver.find_element(By.ID, "kw").send_keys("钟万顺")
        # 5 | sendKeys | id=kw | ${KEY_ENTER} |
        self.driver.find_element(By.ID, "kw").send_keys(Keys.ENTER)
        # 6 | click | linkText=钟万顺 - 惠州市金洺禾装饰工程有限公司 - 法定代表人/高... |  |
        self.vars["window_handles"] = self.driver.window_handles
        # 7 | storeWindowHandle | root |  |
        self.driver.find_element(By.LINK_TEXT, "钟万顺 - 惠州市金洺禾装饰工程有限公司 - 法定代表人/高...").click()
        # 8 | selectWindow | handle=${win2908} |  |
        self.vars["win2908"] = self.wait_for_window(2000)
        # 9 | runScript | window.scrollTo(0,151.1999969482422) |  |
        self.vars["root"] = self.driver.current_window_handle
        # 10 | runScript | window.scrollTo(0,338.3999938964844) |  |
        self.driver.switch_to.window(self.vars["win2908"])
        # 11 | click | css=.aqc-search-tab > span:nth-child(2) |  |
        self.driver.execute_script("window.scrollTo(0,151.1999969482422)")
        # 12 | close |  |  |
        self.driver.execute_script("window.scrollTo(0,338.3999938964844)")
        # 13 | selectWindow | handle=${root} |  |
        self.driver.find_element(By.CSS_SELECTOR, ".aqc-search-tab > span:nth-child(2)").click()
        # 14 | click | css=a:nth-child(4) > .page-item_M4MDr |  |
        self.driver.close()
        # 15 | runScript | window.scrollTo(0,0) |  |
        self.driver.switch_to.window(self.vars["root"])
        # 16 | mouseOver | id=user |  |
        self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(4) > .page-item_M4MDr").click()
        # 17 | mouseOut | id=user |  |
        self.driver.execute_script("window.scrollTo(0,0)")
        # 18 | close |  |  |
        element = self.driver.find_element(By.ID, "user")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.close()
